services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-portfolio}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change_this_password}
      POSTGRES_DB: ${DB_NAME:-portfolio}
    volumes:
      - portfolio_db:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-portfolio} -d ${DB_NAME:-portfolio}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.portfolio-api.rule=Host(`samykhalil.me`) && PathPrefix(`/api`)"
      - "traefik.http.routers.portfolio-api.entrypoints=websecure"
      - "traefik.http.routers.portfolio-api.tls.certresolver=le"
      - "traefik.http.middlewares.portfolio-api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.portfolio-api.middlewares=portfolio-api-strip"
      - "traefik.http.services.portfolio-api.loadbalancer.server.port=4000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.portfolio-frontend.rule=Host(`samykhalil.me`)"
      - "traefik.http.routers.portfolio-frontend.entrypoints=websecure"
      - "traefik.http.routers.portfolio-frontend.tls.certresolver=le"
     # - "traefik.http.services.portfolio-frontend.loadbalancer.server.port=80"
      - "traefik.http.services.portfolio-frontend.loadbalancer.server.port=3000"
volumes:
  portfolio_db:

networks:
  internal:
  traefik_proxy:
    external: true
